server:
  port: 8081

spring:
  application:
    name: naeilmolae-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    config:
      import: classpath:application.yml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org.springframework.web: ERROR
